### ISSUE TITLE
Feature request: apply favourite status to duplicate items

### ISSUE THREAD

**Issue by lissertations** [hughrun/pocketsnack#39]
It occurred to me that if I have duplicate items in my pocket, they were probably things I was particularly interested in reading, and it would be handy to mark them in some way before deduping. Would it be possible for pocketsnack to add dupe items to favourites before the deduping happens? (Such that all dupes are favourited, but all bar one are then deleted)

**Comment by hughrun** [comment]
It shouldn't be too hard to add an optional flag for that. Something like `--fav-and-dedupe` maybe. Or alternatively an extra flag like `--dedupe --fave` which possibly is better because then it could potentially be used in other contexts, like `--stash --fave` to favorite things before stashing them.
